Models/Poll.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CSD412ProjectGroup00000100.Models
{
    public class Poll
    {

        private int _pollId = 0;

        private string _userId = "";

        private string _name = "";

       private string _description = "";

       private Boolean _state = false;

       [Key]
       public int PollId
       {
            get { return _pollId; }
            set { _pollId = value; }
       }
  
        public string UserId
        {
            get { return _userId; }
            set { _userId = value; }
        }
        public virtual ApplicationUser User { get; set; }
        public string Name
        {
            get { return _name; }
            set { _name = value; }
        }
        public string Description
        {
            get { return _description; }
            set { _description = value; }
        }
        public Boolean State
        {
            get { return _state; }
            set { _state = value; }
        }
        public virtual ICollection<Item> Items { get; set; }
    }
}

Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CSD412ProjectGroup00000100.Data;
using CSD412ProjectGroup00000100.Models;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using Microsoft.AspNetCore.Identity;

namespace CSD412ProjectGroup00000100.Controllers
{
    [Authorize]
    public class ItemsController : Controller
    {
        private readonly ApplicationDbContext _context;

        private readonly UserManager<ApplicationUser> _userManager;
        public ItemsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Items
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Items.Include(i => i.Poll);
            return View(await applicationDbContext.ToListAsync());
        }

        [HttpGet]
        public async Task<IActionResult> ViewPollItems(int pollId)
        {
            var applicationDbContext = _context.Items.Include(i => i.Poll).Where(r => r.PollId == pollId);
            ViewData["PollId"] = pollId;
            ViewData["State"] = _context.Polls.Find(pollId).State;
            return View(await applicationDbContext.ToListAsync());
        }

        [HttpPost]
        public JsonResult ShowPollChart(int pollId)
        {
            List<object> iData = new List<object>();
            IQueryable<Item> pollItems = _context.Items.Include(p => p.Votes).Where(r => r.PollId == pollId);


            DataTable dt = new DataTable();
            dt.Columns.Add("Item Name",System.Type.GetType("System.String"));
            dt.Columns.Add("Votes", System.Type.GetType("System.Int32"));
            dt.Columns.Add("Color", System.Type.GetType("System.String"));

            foreach(Item item in pollItems) 
            {
                DataRow dr = dt.NewRow();
                dr["Item Name"] = item.Name;
                dr["Votes"] = item.Votes.Count;
                dr["Color"] = item.ColorValue;
                dt.Rows.Add(dr);
            }

            foreach (DataColumn dc in dt.Columns)
            {
                List<object> x = new List<object>();
                x = (from DataRow drr in dt.Rows select drr[dc.ColumnName]).ToList();
                iData.Add(x);
            }

            return Json(iData);
        }

        // GET: Items/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Items
                .Include(i => i.Poll)
                .FirstOrDefaultAsync(m => m.ItemId == id);
            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        // GET: Items/Create
        public IActionResult Create(int pollId)
        {
            ViewData["PollId"] = pollId;
            return View();
        }

        // POST: Items/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ItemId,PollId,Name,Description,ColorValue")] Item item)
        {
            if (ModelState.IsValid)
            {
                Poll pollHolder = await _context.Polls.FindAsync(item.PollId);
                ApplicationUser user = await _userManager.GetUserAsync(User);
                if (pollHolder.User == user && pollHolder.State == false)
                {
                    _context.Add(item);
                    await _context.SaveChangesAsync();
                }
                return RedirectToAction(nameof(ViewPollItems), new { pollId = item.PollId });
            }
            ViewData["PollId"] = item.PollId;
            return View(item);
        }

        // GET: Items/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Items.FindAsync(id);
            if (item == null)
            {
                return NotFound();
            }
            ViewData["PollId"] = item.PollId;
            return View(item);
        }

        // POST: Items/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ItemId,PollId,Name,Description")] Item item)
        {
            if (id != item.ItemId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    Poll pollHolder = await _context.Polls.FindAsync(item.PollId);
                    ApplicationUser user = await _userManager.GetUserAsync(User);
                    if (pollHolder.User == user && pollHolder.State == false)
                    {
                        _context.Update(item);
                        await _context.SaveChangesAsync();
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ItemExists(item.ItemId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(ViewPollItems), new { pollId = item.PollId });
            }
            ViewData["PollId"] =  item.PollId;
            return View(item);
        }

        // GET: Items/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Items
                .Include(i => i.Poll)
                .FirstOrDefaultAsync(m => m.ItemId == id);
            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        // POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            Item item = await _context.Items.FindAsync(id);
            Poll pollHolder = await _context.Polls.FindAsync(item.PollId);
            ApplicationUser user = await _userManager.GetUserAsync(User);
            if (pollHolder.User == user && pollHolder.State == false)
            {
                _context.Items.Remove(item);
                await _context.SaveChangesAsync();
                
            }
            return RedirectToAction(nameof(Index));
        }

        private bool ItemExists(int id)
        {
            return _context.Items.Any(e => e.ItemId == id);
        }


    }
}

Controllers/PollsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CSD412ProjectGroup00000100.Data;
using CSD412ProjectGroup00000100.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using System.Collections;

namespace CSD412ProjectGroup00000100.Controllers
{
    [Authorize]
    public class PollsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public PollsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Polls
        public async Task<IActionResult> Index()
        {
            ApplicationUser theUser = await _userManager.GetUserAsync(User);
            IQueryable<Poll> applicationDbContext = _context.Polls.Include(p => p.User).Where(r => r.User == theUser);
            return View(await applicationDbContext.ToListAsync());
        }
        public async Task<IActionResult> AllPolls()
        {
            IQueryable<Poll> applicationDbContext = _context.Polls.Include(p => p.User).Where(r => r.State == true);
            return View(await applicationDbContext.ToListAsync());
        }
        // GET: Polls/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            ApplicationUser theUser = await _userManager.GetUserAsync(User);
            if (id == null)
            {
                return NotFound();
            }

            var poll = await _context.Polls.Include(p => p.Items).FirstOrDefaultAsync(m => m.PollId == id);
            if (poll == null)
            {
                return NotFound();
            }

            
            var model = new ViewPoll { CurrentPoll = poll, Items = poll.Items.ToArray() };

            // check if the user has any votes 
            foreach (Item item in poll.Items.ToArray())
            {
                var vote = _context.Votes.Include(p => p.Item).Where(x => x.Voter == theUser && x.Item == item);
                if (vote.Count() >= 1) 
                {
                    // a vote exists set show results to true  
                    model.ShowResult = true;
                    break;
                }
            }  
            // if there is any votes result 
            if (model.ShowResult) {
                List<object> iData = new List<object>();
                DataTable dt = new DataTable();
                dt.Columns.Add("Item Name", System.Type.GetType("System.String"));
                dt.Columns.Add("Votes", System.Type.GetType("System.Int32"));
                dt.Columns.Add("Color", System.Type.GetType("System.String"));
                foreach (Item item in poll.Items.ToArray())
                {
                    DataRow dr = dt.NewRow();
                    dr["Item Name"] = item.Name;
                    dr["Votes"] = _context.Votes.Include(p => p.Item).Where(x => x.Item == item).Count();// test value 
                    dr["Color"] = item.ColorValue;
                    dt.Rows.Add(dr);
                }
                foreach (DataColumn dc in dt.Columns)
                {
                    List<object> x = new List<object>();
                    x = (from DataRow drr in dt.Rows select drr[dc.ColumnName]).ToList();
                    iData.Add(x);
                }
                ViewBag.labels = iData.ElementAt(0);
                ViewBag.data = iData.ElementAt(1);
                ViewBag.color = iData.ElementAt(2);
            }
            return View(model);
        }

        // GET: Polls/Create
        public IActionResult Create()
        {
            ViewData["UserId"] = new SelectList(_context.Set<ApplicationUser>(), "Id", "Id");
            return View();
        }

        // POST: Polls/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Description")] Poll poll)
        {
            if (ModelState.IsValid)
            {
                poll.User = await _userManager.GetUserAsync(User);
                poll.State = false;
                _context.Add(poll);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Set<ApplicationUser>(), "Id", "Id", poll.UserId);
            return View(poll);
        }

        // GET: Polls/Edit/5
        
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Poll poll = await _context.Polls.FindAsync(id);
            if (poll == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.Set<ApplicationUser>(), "Id", "Id", poll.UserId);
            return View(poll);
        }

        // POST: Polls/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PollId,Name,Description")] Poll poll)
        {
            if (id != poll.PollId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    Poll pollHolder = await _context.Polls.FindAsync(id);
                    ApplicationUser user = await _userManager.GetUserAsync(User);
                    if (pollHolder.User == user && pollHolder.State == false)
                    {
                        pollHolder.Name = poll.Name;
                        pollHolder.Description = poll.Description;
                        _context.Update(pollHolder);
                        await _context.SaveChangesAsync();
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PollExists(poll.PollId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Set<ApplicationUser>(), "Id", "Id", poll.UserId);
            return View(poll);
        }

        // GET: Polls/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var poll = await _context.Polls
                .Include(p => p.User)
                .FirstOrDefaultAsync(m => m.PollId == id);
            if (poll == null)
            {
                return NotFound();
            }

            return View(poll);
        }

        // POST: Polls/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            Poll poll = await _context.Polls.FindAsync(id);
            ApplicationUser user = await _userManager.GetUserAsync(User);
            if (poll.User == user)
            {
                _context.Polls.Remove(poll);
                await _context.SaveChangesAsync();
                
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: Polls/State/5
        public async Task<IActionResult> State(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var poll = await _context.Polls
                .Include(p => p.User)
                .FirstOrDefaultAsync(m => m.PollId == id);
            if (poll == null)
            {
                return NotFound();
            }

            return View(poll);
        }
        [HttpPost, ActionName("State")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> StateConfirmed(int id)
        {
            Poll poll = await _context.Polls.FindAsync(id);
            ApplicationUser user = await _userManager.GetUserAsync(User);
            if (poll.User == user)
            {
                _context.Polls.Find(id).State = true;
                await _context.SaveChangesAsync();
                
            }
            return RedirectToAction(nameof(Index));
        }
        private bool PollExists(int id)
        {
            return _context.Polls.Any(e => e.PollId == id);
        }
    }
}

Views/Polls/AllPolls.cshtml
@model IEnumerable<CSD412ProjectGroup00000100.Models.Poll>

@{
    ViewData["Title"] = "AllPoll";
}

<h1>AllPoll</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>   
                <a asp-action="Details" asp-route-id="@item.PollId">Details</a> 
            </td>
        </tr>
}
    </tbody>
</table>

Views/Polls/Create.cshtml
@model CSD412ProjectGroup00000100.Models.Poll

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Poll</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Polls/Delete.cshtml
@model CSD412ProjectGroup00000100.Models.Poll

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Poll</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.State)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.State)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="PollId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Polls/Details.cshtml
@model CSD412ProjectGroup00000100.Models.ViewPoll

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>
<div>
    <h4>Poll</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CurrentPoll.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CurrentPoll.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CurrentPoll.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CurrentPoll.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CurrentPoll.State)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CurrentPoll.State)
        </dd>
    </dl>
</div>
<div>
    <a asp-controller="Items" asp-action="ViewPollItems" asp-route-pollId="@Model.CurrentPoll.PollId">View Items</a> |
    <a asp-action="AllPolls">Back to All Polls</a> |
    <a asp-action="Index">Back to My Polls</a> 
    @if (@Model.CurrentPoll.State == false)
    {
        <a asp-controller="Items" asp-action="Create" asp-route-pollId="@Model.CurrentPoll.PollId">| Add Item</a>
        <a asp-controller="Polls" asp-action="State" asp-route-id="@Model.CurrentPoll.PollId">| change state</a>
        <a asp-controller="Polls" asp-action="Edit" asp-route-id="@Model.CurrentPoll.PollId">| Edit</a>
    }
</div>
<h1>Items</h1>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Items.FirstOrDefault().Poll)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Items.FirstOrDefault().Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Items.FirstOrDefault().Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Items)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Poll.PollId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    <a asp-controller="Items" asp-action="Details" asp-route-id="@item.ItemId">Details</a>
                    @if (@Model.CurrentPoll.State == false)
                    {
                        <a asp-controller="Items" asp-action="Edit" asp-route-id="@item.ItemId">| Edit</a>
                        <a asp-controller="Items" asp-action="Delete" asp-route-id="@item.ItemId">| Delete </a>
                    }
                    else if (@Model.ShowResult == false)
                    {
                        <a asp-controller="Votes" asp-action="Create" asp-route-itemId="@item.ItemId">| Vote</a>
                    }
                    else
                    {
                        // TODO add the percentage of votes per item 
                    }
                </td>
            </tr>
        }
    </tbody>
</table>
@if (@Model.ShowResult == true)
{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.6.0/Chart.min.js" type="text/javascript"></script>
    <script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>


    <canvas id="myPieChart" style="padding: 0;margin: auto;display: block;height:40vh; width:80vw"> </canvas>
    <wbr>
    <canvas id="myBarChart" style="padding: 0;margin: auto;display: block;height:40vh; width:80vw"> </canvas>
    <script>
        var myLabels = [];
        var myColor = [];
        var myData = [];

        @foreach (var d in ViewBag.labels)
        {
            @:myLabels.push("@d");
        }
        @foreach (var d in ViewBag.data)
        {
            @:myData.push("@d");
        } @foreach (var d in ViewBag.Color)
        {
            @:myColor.push("@d");
        }
        var pie = document.getElementById('myPieChart').getContext('2d');
        var myChart = new Chart(pie, {
            type: 'pie',
            data: {

                datasets: [{
                    label: 'Poll Pie Results',
                    backgroundColor: myColor,
                    borderColor: 'rgb(0, 0, 0)',
                    data: myData,
                    order: 1
                }],
                labels: myLabels
            },

            options: {}
        });
        var bar = document.getElementById('myBarChart').getContext('2d');
        var myChart = new Chart(bar, {
            type: 'bar',
            data: {

                datasets: [{
                    label: 'Poll Bar Results',
                    backgroundColor: myColor,
                    borderColor: 'rgb(0, 0, 0)',
                    data: myData,
                    order: 1
                }],
                labels: myLabels
            },

            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                        }
                    }]
                }
            }
        });
    
    </script>

}

Views/Polls/Edit.cshtml
@model CSD412ProjectGroup00000100.Models.Poll

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Poll</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PollId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Polls/Index.cshtml
@model IEnumerable<CSD412ProjectGroup00000100.Models.Poll>

@{
    ViewData["Title"] = "Index";
}

<h1>Your Polls</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.State)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.State)
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.PollId">Details</a> 
                <a asp-action="Delete" asp-route-id="@item.PollId">| Delete</a> 
                @if (item.State == false)
                {
                  <a asp-controller="Items" asp-action="Create" asp-route-pollId="@item.PollId">| Add Item</a> 
                  <a asp-controller="Polls" asp-action="State" asp-route-id="@item.PollId">| change state</a>
                  <a asp-controller="Polls" asp-action="Edit" asp-route-id="@item.PollId">| Edit</a>
                }
            </td>
        </tr>
}
    </tbody>
</table>

Views/Polls/State.cshtml
@model CSD412ProjectGroup00000100.Models.Poll

@{
    ViewData["Title"] = "State";
}

<h1>State</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Poll</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.State)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.State)
        </dd>
    </dl>
    
    <form asp-action="State">
        <input type="hidden" asp-for="PollId" />
        <input type="submit" value="State" class="btn btn-danger" /> |
        <a asp-action="Index">Back to myList</a>
    </form>
</div>